/**
 * Resend, with fixed templates and fixed recipients. The model never chooses a recipient and never
 * writes a body (invariant 7): it can only open a form. Every template below is a pure function of
 * validated form fields, and each one is sent only after `can_send_email` has consumed a unit of the
 * daily budget.
 */
import { Resend } from "resend";

export const SUMMARY_FOOTER = "Generated by an AI system on abdelrahmansheta.com";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export interface SendResult {
  ok: boolean;
  reason?: string;
}

/** Low-level send. Returns a result instead of throwing; the caller decides what a failure means. */
export async function send(input: {
  to: string;
  subject: string;
  text: string;
  replyTo?: string;
}): Promise<SendResult> {
  const key = process.env.RESEND_API_KEY ?? "";
  const from = process.env.RESEND_FROM ?? "portfolio@send.abdelrahmansheta.com";
  if (key === "") return { ok: false, reason: "email_unavailable" };

  try {
    const result = await new Resend(key).emails.send({
      from,
      to: input.to,
      subject: input.subject,
      text: input.text,
      html: `<pre style="font:14px/1.6 ui-monospace,monospace;white-space:pre-wrap">${escapeHtml(input.text)}</pre>`,
      ...(input.replyTo !== undefined ? { replyTo: input.replyTo } : {}),
    });
    return result.error === null ? { ok: true } : { ok: false, reason: "email_failed" };
  } catch {
    return { ok: false, reason: "email_failed" };
  }
}

export function messageTemplate(input: { name: string; email: string; body: string; sessionId: string }): string {
  return [
    "A visitor left a message on abdelrahmansheta.com.",
    "",
    `Name:    ${input.name}`,
    `E-mail:  ${input.email}`,
    `Session: ${input.sessionId}`,
    "",
    "Message:",
    input.body,
  ].join("\n");
}

export function leadTemplate(input: {
  name: string;
  company: string | null;
  email: string;
  note: string | null;
  sessionId: string;
}): string {
  return [
    "New lead from abdelrahmansheta.com.",
    "",
    `Name:    ${input.name}`,
    `Company: ${input.company ?? "-"}`,
    `E-mail:  ${input.email}`,
    `Session: ${input.sessionId}`,
    "",
    `Note:    ${input.note ?? "-"}`,
  ].join("\n");
}

export function summaryTemplate(summary: string): string {
  return [
    "Here is the summary of your conversation with the AI version of Abdelrahman.",
    "",
    summary.trim(),
    "",
    "-- ",
    SUMMARY_FOOTER,
  ].join("\n");
}
