/**
 * Writes .env.vercel (gitignored): a ready-to-paste block for Vercel's environment-variable UI.
 *
 * Exists because the list is not `.env.example`. That file documents everything the code can read,
 * including local-dev-only and script-only variables — and two of them are actively harmful in a
 * deployment: KNOWLEDGE_DIR breaks the corpus fetch, ALLOW_EXAMPLE_CORPUS publishes the example
 * person. Copying `.env.example` to Vercel is the obvious move and the wrong one, so this generates
 * the correct list instead of relying on anyone reading a warning.
 *
 * Secrets are generated fresh rather than copied from `.env.local`: a local secret has usually been
 * on a screen, in a shell history, or in a transcript.
 *
 *   pnpm env:vercel
 */
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(repoRoot, ".env.vercel");

const SUPABASE_URL = "https://zpppersjjcoefcemidmw.supabase.co";
const ALIBABA = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1";

function readLocal(): Record<string, string> {
  const out: Record<string, string> = {};
  let raw: string;
  try {
    raw = readFileSync(path.join(repoRoot, ".env.local"), "utf8");
  } catch {
    return out;
  }
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.length === 0 || trimmed.startsWith("#") || !trimmed.includes("=")) continue;
    const eq = trimmed.indexOf("=");
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).split("#")[0].trim();
  }
  return out;
}

const secret = (): string => randomBytes(24).toString("hex");

function main(): void {
  const local = readLocal();
  const pick = (key: string, fallback = ""): string => local[key] ?? fallback;

  const body = `# Paste into Vercel: Project -> Settings -> Environment Variables.
# The UI accepts a whole .env block at once. Tick Production AND Preview, and mark every row
# Sensitive. Generated by \`pnpm env:vercel\` from what the code actually reads.

# --- 1. FILL THESE TWO YOURSELF -------------------------------------------------
# Fine-grained GitHub PAT: abdelrahmansheta16/portfolio-corpus only, Contents: Read-only.
# The production build FAILS without it, on purpose.
CORPUS_REPO_TOKEN=
# The secret / service_role key, NOT a publishable one:
# ${SUPABASE_URL.replace("https://", "https://supabase.com/dashboard/project/").replace(".supabase.co", "/settings/api-keys")}
SUPABASE_SERVICE_ROLE_KEY=

# --- 2. Database ----------------------------------------------------------------
SUPABASE_URL=${SUPABASE_URL}

# --- 3. The brain ---------------------------------------------------------------
# Both slots are one Alibaba Model Studio (Singapore) account; only the model differs.
LLM_PRIMARY_API_KEY=${pick("LLM_PRIMARY_API_KEY")}
LLM_PRIMARY_BASE_URL=${pick("LLM_PRIMARY_BASE_URL", ALIBABA)}
LLM_PRIMARY_MODEL=${pick("LLM_PRIMARY_MODEL", "deepseek-v4-flash")}
LLM_FALLBACK_API_KEY=${pick("LLM_FALLBACK_API_KEY")}
LLM_FALLBACK_BASE_URL=${pick("LLM_FALLBACK_BASE_URL", ALIBABA)}
LLM_FALLBACK_MODEL=${pick("LLM_FALLBACK_MODEL", "qwen3.8-flash")}

# --- 4. Secrets, generated fresh (deliberately not your local values) ------------
VISITOR_COOKIE_SECRET=${secret()}
IP_HASH_SALT=${secret()}
CRON_SECRET=${secret()}
LLM_ADAPTER_SECRET=${secret()}

# --- 5. Site behaviour ----------------------------------------------------------
NEXT_PUBLIC_VOICE_ENABLED=0
OWNER_EMAIL=${pick("OWNER_EMAIL")}

# --- 6. Optional: email delivery ------------------------------------------------
# Without these a visitor's message is still STORED, just not mailed, and the daily
# digest is skipped. Nothing errors.
# RESEND_API_KEY=
# RESEND_FROM=portfolio@send.abdelrahmansheta.com

# --- 7. Deliberately NOT set on Vercel ------------------------------------------
# KNOWLEDGE_DIR          local dev only; setting it BREAKS the corpus fetch.
# ALLOW_EXAMPLE_CORPUS   would publish the example person under your name.
# SITE_URL               read only by scripts/push-agent-config.ts, never by the app.
# ELEVENLABS_*           voice is off; each of those paths degrades cleanly.
# ANTHROPIC_API_KEY      optional third fallback, used only if LLM_FALLBACK_API_KEY is unset.
# NEXT_PUBLIC_CAL_URL    only once there is a real Cal.com link.
`;

  writeFileSync(OUT, body, "utf8");
  process.stdout.write(`wrote ${path.relative(repoRoot, OUT)}\n`);

  const blank = ["LLM_PRIMARY_API_KEY", "LLM_FALLBACK_API_KEY", "OWNER_EMAIL"].filter(
    (k) => pick(k).length === 0,
  );
  if (blank.length > 0) {
    process.stdout.write(`not found in .env.local, fill by hand: ${blank.join(", ")}\n`);
  }
  process.stdout.write("still blank by design: CORPUS_REPO_TOKEN, SUPABASE_SERVICE_ROLE_KEY\n");
}

main();
